CREATE TABLE CLIENTES (
		ID BIGINT NOT NULL AUTO_INCREMENT,
        NOME VARCHAR(100),
        PLANO_EXCLUSIVE BIT,
        SALDO NUMERIC(38,2),      
        NUMERO_DA_CONTA VARCHAR(20),
        DATA_DE_NASCIMENTO DATE,  
        
         PRIMARY KEY(ID)
)